name: Update And Release

on:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@2.3.1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: npm install and release
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: npm run release
